u

diff --git a/.github/workflows/pr-qa.yml b/.github/workflows/pr-qa.yml
--- a/.github/workflows/pr-qa.yml
+++ b/.github/workflows/pr-qa.yml
@@ -47,49 +47,49 @@ jobs:
           cat only-apex-test-class.txt
           
 
-      - name: QA Validation
-        shell: bash
-        run: |
-          echo "QA Validation Start"
+      # - name: QA Validation
+      #   shell: bash
+      #   run: |
+      #     echo "QA Validation Start"
           
-          #!/bin/bash
-          test_classes_string=""
-          missing_test_class=false
-          while IFS= read -r class || [ -n "$class" ]; do
-              if [[ "$class" == *Test ]]; then
-                  test_classes_string+="${class} "
-              else
-                  test_class="${class}Test"
-                  if grep -q "^${test_class}$" only-apex-test-class.txt; then
-                      test_classes_string+="${test_class} "
-                  else
-                      echo "Error: Test class for ${class} is missing."
-                      missing_test_class=true
-                  fi             
-              fi
-          done < all-apex-class.txt
+      #     #!/bin/bash
+      #     test_classes_string=""
+      #     missing_test_class=false
+      #     while IFS= read -r class || [ -n "$class" ]; do
+      #         if [[ "$class" == *Test ]]; then
+      #             test_classes_string+="${class} "
+      #         else
+      #             test_class="${class}Test"
+      #             if grep -q "^${test_class}$" only-apex-test-class.txt; then
+      #                 test_classes_string+="${test_class} "
+      #             else
+      #                 echo "Error: Test class for ${class} is missing."
+      #                 missing_test_class=true
+      #             fi             
+      #         fi
+      #     done < all-apex-class.txt
 
 
          
-          test_classes_string=$(echo "$test_classes_string" | sed 's/ $//')
-          test_classes_string=$(echo "$test_classes_string" | awk '{for(i=1;i<=NF;i++) if(!seen[$i]++) printf "%s ", $i; print ""}')
-          if [ "$missing_test_class" = true ]; then
-              exit 1
-          else
-              echo "Test classes found: $test_classes_string"
-          fi
+      #     test_classes_string=$(echo "$test_classes_string" | sed 's/ $//')
+      #     test_classes_string=$(echo "$test_classes_string" | awk '{for(i=1;i<=NF;i++) if(!seen[$i]++) printf "%s ", $i; print ""}')
+      #     if [ "$missing_test_class" = true ]; then
+      #         exit 1
+      #     else
+      #         echo "Test classes found: $test_classes_string"
+      #     fi
 
           
 
-          if [ "$test_classes_string" = "" ]; then
-            echo "INSIDE IF"
-            sf project deploy validate -x output/package/package.xml --post-destructive-changes output/destructiveChanges/destructiveChanges.xml -o test-aqzkekn5j4iv@example.com -w 30 
-          else
-            echo "INSIDE ELSE"
-            sf project deploy validate -x output/package/package.xml --post-destructive-changes output/destructiveChanges/destructiveChanges.xml -l RunSpecifiedTests -t $test_classes_string -o test-aqzkekn5j4iv@example.com -w 30
-          fi
-          echo "QA Validation is Successful"
-          ls -R output/force-app/main/default
+      #     if [ "$test_classes_string" = "" ]; then
+      #       echo "INSIDE IF"
+      #       sf project deploy validate -x output/package/package.xml --post-destructive-changes output/destructiveChanges/destructiveChanges.xml -o test-aqzkekn5j4iv@example.com -w 30 
+      #     else
+      #       echo "INSIDE ELSE"
+      #       sf project deploy validate -x output/package/package.xml --post-destructive-changes output/destructiveChanges/destructiveChanges.xml -l RunSpecifiedTests -t $test_classes_string -o test-aqzkekn5j4iv@example.com -w 30
+      #     fi
+      #     echo "QA Validation is Successful"
+      #     ls -R output/force-app/main/default
 
   salesforce-code-analyzer-v4:
     name: SCA v4
@@ -110,7 +110,7 @@ jobs:
         uses: forcedotcom/run-code-analyzer@v1
         with:
           run-command: run
-          run-arguments: --engine pmd,eslint --normalize-severity --target output/force-app/main/default/
+          run-arguments: --engine pmd,eslint --normalize-severity --target output/force-app/main/default/ --format html --outfile result1.html
           results-artifact-name: salesforce-code-analyzer1-results
 
       - name: Check the outputs to determine whether to fail
@@ -120,31 +120,31 @@ jobs:
           steps.run-code-analyzer.outputs.num-violations > 10
         run: exit 1
   
-  # salesforce-code-analyzer-v5:
-  #   needs: validation-with-code-coverage
-  #   name: SCA v5
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Check out files
-  #       uses: actions/checkout@v4
+  salesforce-code-analyzer-v5:
+    needs: validation-with-code-coverage
+    name: SCA v5
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out files
+        uses: actions/checkout@v4
 
-  #     - name: Install Salesforce CLI
-  #       run: npm install -g @salesforce/cli@latest
+      - name: Install Salesforce CLI
+        run: npm install -g @salesforce/cli@latest
 
-  #     - name: Install Salesforce Code Analyzer v5.x CLI Plugin
-  #       run: sf plugins install code-analyzer@latest
+      - name: Install Salesforce Code Analyzer v5.x CLI Plugin
+        run: sf plugins install code-analyzer@latest
 
-  #     - name: Run Salesforce Code Analyzer
-  #       id: run-code-analyzer
-  #       uses: forcedotcom/run-code-analyzer@v2
-  #       with:
-  #         run-arguments: --workspace output/force-app/main/default/ --view detail --output-file sfca_results.html --output-file sfca_results.json
-  #         results-artifact-name: salesforce-code-analyzer2-results
+      - name: Run Salesforce Code Analyzer
+        id: run-code-analyzer
+        uses: forcedotcom/run-code-analyzer@v2
+        with:
+          run-arguments: --workspace output/force-app/main/default/ --view detail --output-file results2.html
+          results-artifact-name: salesforce-code-analyzer2-results
 
-  #     - name: Check the outputs to determine whether to fail
-  #       if: |
-  #         steps.run-code-analyzer.outputs.exit-code > 0 ||
-  #         steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
-  #         steps.run-code-analyzer.outputs.num-sev2-violations > 0 ||
-  #         steps.run-code-analyzer.outputs.num-violations > 10
-  #       run: exit 1
+      - name: Check the outputs to determine whether to fail
+        if: |
+          steps.run-code-analyzer.outputs.exit-code > 0 ||
+          steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
+          steps.run-code-analyzer.outputs.num-sev2-violations > 0 ||
+          steps.run-code-analyzer.outputs.num-violations > 10
+        run: exit 1
