u

diff --git a/.github/workflows/pr-qa.yml b/.github/workflows/pr-qa.yml
--- a/.github/workflows/pr-qa.yml
+++ b/.github/workflows/pr-qa.yml
@@ -46,24 +46,24 @@ jobs:
           chmod 777 only-apex-test-class.txt
           cat only-apex-test-class.txt
           chmod 777 output
-      - name: Install Salesforce Code Analyzer v4.x CLI Plugin
-        run: |
-          sf plugins install @salesforce/sfdx-scanner@latest
+      # - name: Install Salesforce Code Analyzer v4.x CLI Plugin
+      #   run: |
+      #     sf plugins install @salesforce/sfdx-scanner@latest
 
-      - name: Run Salesforce Code Analyzer
-        id: run-code-analyzer
-        uses: forcedotcom/run-code-analyzer@v1
-        with:
-          run-command: run
-          run-arguments: --engine pmd,eslint --normalize-severity --target output/force-app/main/default/ --format html --outfile result1.html
-          results-artifact-name: salesforce-code-analyzer1-results
+      # - name: Run Salesforce Code Analyzer
+      #   id: run-code-analyzer
+      #   uses: forcedotcom/run-code-analyzer@v1
+      #   with:
+      #     run-command: run
+      #     run-arguments: --engine pmd,eslint --normalize-severity --target output/force-app/main/default/ --format html --outfile result1.html
+      #     results-artifact-name: salesforce-code-analyzer1-results
 
-      - name: Check the outputs to determine whether to fail
-        if: |
-          steps.run-code-analyzer.outputs.exit-code > 0 ||
-          steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
-          steps.run-code-analyzer.outputs.num-violations > 10
-        run: exit 1
+      # - name: Check the outputs to determine whether to fail
+      #   if: |
+      #     steps.run-code-analyzer.outputs.exit-code > 0 ||
+      #     steps.run-code-analyzer.outputs.num-sev1-violations > 0 ||
+      #     steps.run-code-analyzer.outputs.num-violations > 10
+      #   run: exit 1
       
       - name: Install Salesforce Code Analyzer v5.x CLI Plugin
         run: |
